# -*- coding: utf-8 -*-
"""HousePrice_Pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DOwVenE_j01Su-1a_mvwrVj3Rs7XOfpb
"""

# Import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Load dataset
df = pd.read_csv("/content/Bengaluru_House_Data.csv")
df.head()

# Select simple columns
data = data[['total_sqft', 'bath', 'price']]

# Remove missing values
data = data.dropna()

# Convert total_sqft to numeric
data['total_sqft'] = pd.to_numeric(data['total_sqft'], errors='coerce')

# Remove invalid rows
data = data.dropna()

# Features and Target
X = data[['total_sqft', 'bath']]
y = data['price']

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict
prediction = model.predict([[1200, 2]])

print("Predicted House Price (Lakhs):", prediction[0])